### PR TITLE
ARM OSX Migrator + Updates

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/dcm2niix-feedstock/pull/16

### CODE REVIEW

**Comment by hoechenberger** [comment]
Still failing :(

**Comment by larsoner** [comment]
Probably, but I'm not sure how to do it at the build level here :(

**Comment by larsoner** [comment]
Green, nicely done @hoechenberger !

@kastman @ningfei feel free to merge if you're happy. This ended up just being the bot-produced #16 plus a commit to avoid static linking

**Comment by kastman** [comment]
Thanks for figuring that out! Any idea why static linking started breaking in this commit? CMake version wasn't fixed or similar?

**Review by kastman — APPROVED** [review]

**Comment by hoechenberger** [comment]
@kastman I have no idea :/

**Pull request merged**
